# Generated by Django 5.2.1 on 2025-05-12 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('due_soon', 'Book Due Soon'), ('overdue', 'Book Overdue'), ('new_book', 'New Book Added'), ('status_change', 'Book Status Change'), ('fine', 'Fine Notification'), ('suspension', 'Account Suspension'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
