# Generated by Django 5.2.1 on 2025-07-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_books', '0003_book_table_of_contents'),
        ('fbc_fines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbc_books.book'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(choices=[('overdue', 'Overdue Book'), ('damage', 'Book Damage'), ('lost', 'Lost Book'), ('general', 'General Fine'), ('other', 'Other')], default='general', max_length=10),
        ),
    ]
