repos:
  - repo: https://github.com/zricethezav/gitleaks-pre-commit
    rev: v1.0.0
    hooks:
      - id: gitleaks
        args: ['--config=.gitleaks.toml']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
