# Generated by Django 5.2.1 on 2025-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_users', '0004_add_activity_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#00843D', help_text='Hex code for FBC Green or chosen primary color.', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_suspend_users', 'Can suspend users'), ('can_manage_ebooks', 'Can manage e-books'), ('can_view_reports', 'Can view reports'), ('can_manage_payments', 'Can manage payments'), ('can_view_attendance', 'Can view attendance logs')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
