# Generated by Django 5.2.1 on 2025-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_users', '0005_systemsettings_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Site favicon (small icon)', null=True, upload_to='system/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='System logo for sidebar and header', null=True, upload_to='system/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='FBC Library System', help_text='Name of the library system', max_length=100),
        ),
    ]
