# Generated by Django 5.2.1 on 2025-07-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_users', '0006_systemsettings_favicon_systemsettings_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='footer_color',
            field=models.CharField(default='#6c757d', help_text='Color for the footer section', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='header_color',
            field=models.CharField(default='#343a40', help_text='Color for the header navigation', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_color',
            field=models.CharField(default='#28a745', help_text='Color for the sidebar navigation', max_length=7),
        ),
    ]
