# Generated by Django 5.2.1 on 2025-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='table_of_contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
