# Generated by Django 5.2.1 on 2025-06-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_fines', '0001_initial'),
        ('fbc_payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='fine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='fbc_fines.fine'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('orange_money', 'Orange Money'), ('afrimoney', 'Afrimoney'), ('qmoney', 'QMoney'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
