# Generated by Django 5.2.1 on 2025-09-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbc_payments', '0003_paymentdetail_fine_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Store payment details like cardholder name'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='fbc_payments.payment'),
        ),
    ]
