name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Vercel (if VERCEL_TOKEN present)
        if: secrets.VERCEL_TOKEN != ''
        run: |
          echo "VERCEL token found - deploying to Vercel..."
          npm install -g vercel@25 || true
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Skip deploy when no token
        if: secrets.VERCEL_TOKEN == ''
        run: |
          echo "No VERCEL_TOKEN secret configured. Skipping automatic Vercel deploy."
